const DATA_URL = "./data/exams-2026-june.json";

const BOARD_ORDER = ["Edexcel", "CIE"];

const I18N = {
  zh: {
    langButton: "Switch to English",
    headerTitle: "2026 June 考试日历生成器",
    headerSubtitle:
      "支持 Edexcel IAL、Edexcel IGCSE、Cambridge IGCSE、Cambridge AS/A2。勾选后自动冲突处理并即时预览，可导出 PNG 和 ICS。",
    revisionLabel: "备考复习资料 / Revision Notes:",
    pickerTitle: "科目选择",
    searchLabel: "搜索考试 / 科目 / 代码",
    searchPlaceholder: "例如：WMA11 / Mathematics / Biology",
    levelFilter: { ALL: "全部", IG: "IG", AS: "AS", A2: "A2" },
    actionSelectVisible: "全选当前筛选",
    actionClearVisible: "清空当前筛选",
    actionManualRefresh: "手动刷新（可选）",
    previewTitle: "已选考试预览",
    alertToggleLabel: "添加考前提醒（1天前 & 2小时前）",
    exportPng: "生成图片 (.png)",
    exportIcs: "生成日历 (.ics)",
    cardTitle: "Personal Exam Calendar",
    footerText: "2026 June External Exam Timetable • Unofficial Tool",
    loadingData: "正在加载考试数据...",
    selectPrompt: "请先勾选考试，右侧会自动预览。",
    loadedRange: (count, start, end) => `已加载 ${count} 场考试（${start} 至 ${end}）`,
    loadFailed: "加载数据失败，请检查 data/exams-2026-june.json 是否存在。",
    noResults: "没有匹配结果，请尝试其他关键词。",
    stats: (selected, total, visible, selectedVisible) =>
      `已选择 ${selected}/${total} 场考试；当前筛选显示 ${visible} 场（其中已选 ${selectedVisible} 场）`,
    levelLabel: { IG: "IG", AS: "AS", A2: "A2" },
    levelCount: (count) => `${count} 场考试`,
    levelSelect: "全选",
    levelClear: "清空",
    boardLabel: { Edexcel: "Edexcel / EDX", CIE: "Cambridge / CIE" },
    boardShort: { Edexcel: "EDX", CIE: "CIE" },
    cieIncludeAll: "勾选后自动包含该学科全部卷子",
    paperCount: (count) => `${count} 张卷`,
    ciePaperSummary: (count, paperTypes) => `${count} 张卷: ${paperTypes}`,
    moreTypes: (count) => `+${count}项`,
    paperType: {
      multiple: "选择题",
      structure: "结构化",
      experiment: "实验",
      reading: "阅读",
      writing: "写作",
      readingWriting: "读写",
      listening: "听力",
      speaking: "口语",
      literature: "文学",
      essayData: "论述/数据分析",
      coursework: "课程作业",
      pureMath: "纯数",
      mechanics: "力学",
      statistics: "统计",
    },
    paperJoiner: " + ",
    noSelection: "你还没有选择考试。请先勾选上方考试卡片。",
    needSelection: "未生成：请先选择至少 1 场考试。",
    unresolvedStatus: (count) => `已生成日历，但仍有 ${count} 组冲突无法自动调整，请人工确认。`,
    generatedStatus: "已生成个性化日历，可直接导出 PNG 或 ICS。",
    noDisplay: "没有可展示的考试项。",
    summaryLabel: {
      examCount: "考试数量",
      autoAdjusted: "自动调整场次",
      supervisedBreak: "Supervised Break",
      dateRange: "日期范围",
      initialConflicts: "初始冲突数",
    },
    warningAdjusted: "自动切换到 S2/S3：",
    warningUnresolved: "仍需人工处理的冲突：",
    breakTitle: "Supervised Break",
    minuteUnit: "分钟",
    notePrefix: "备注",
    exportPngNeed: "请先生成日历后再导出 PNG。",
    exportPngMissingLib: "导出 PNG 失败：html2canvas 未加载成功。请联网后重试。",
    exportPngBlobFail: "导出 PNG 失败：无法生成图片数据。",
    exportPngSuccess: "PNG 导出成功。",
    exportPngFail: "导出 PNG 失败，请稍后重试。",
    exportIcsNeed: "请先生成日历后再导出 ICS。",
    exportIcsSuccessWithAlerts: "ICS 导出成功（已包含提醒）。",
    exportIcsSuccessNoAlerts: "ICS 导出成功（未添加提醒）。",
    reminderTomorrow: (code) => `提醒：${code} 明天考试`,
    reminderTwoHours: (code) => `提醒：${code} 2小时后开考`,
    imgTitle: "2026 考试时间表",
    imgSubtitle: "June 2026 Personal Exam Plan",
    imgExamCount: (count) => `共 ${count} 场考试`,
    imgThDate: "日期",
    imgThTime: "时间",
    imgThSubject: "科目 / 单元",
    imgThVenue: "考场",
    imgArrival: "到达时间",
    imgFooter: "Generated by 2026 Exam Calendar Tool",
    weekdays: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
  },
  en: {
    langButton: "切换为中文",
    headerTitle: "2026 June Exam Calendar Generator",
    headerSubtitle:
      "Supports Edexcel IAL, Edexcel IGCSE, Cambridge IGCSE, and Cambridge AS/A2. Selections are auto-processed for clashes and previewed instantly.",
    revisionLabel: "Revision Notes:",
    pickerTitle: "Subject Selection",
    searchLabel: "Search exams / subjects / codes",
    searchPlaceholder: "e.g. WMA11 / Mathematics / Biology",
    levelFilter: { ALL: "All", IG: "IG", AS: "AS", A2: "A2" },
    actionSelectVisible: "Select visible",
    actionClearVisible: "Clear visible",
    actionManualRefresh: "Manual refresh (optional)",
    previewTitle: "Selected Exam Preview",
    alertToggleLabel: "Add reminders (1 day & 2 hours before)",
    exportPng: "Save image (.png)",
    exportIcs: "Get calendar (.ics)",
    cardTitle: "Personal Exam Calendar",
    footerText: "2026 June External Exam Timetable • Unofficial Tool",
    loadingData: "Loading exam data...",
    selectPrompt: "Select exams to start live preview.",
    loadedRange: (count, start, end) => `Loaded ${count} exams (${start} to ${end})`,
    loadFailed: "Failed to load data. Check data/exams-2026-june.json.",
    noResults: "No matching exams. Try another keyword.",
    stats: (selected, total, visible, selectedVisible) =>
      `Selected ${selected}/${total}; showing ${visible} (${selectedVisible} selected in current view)`,
    levelLabel: { IG: "IG", AS: "AS", A2: "A2" },
    levelCount: (count) => `${count} exams`,
    levelSelect: "Select",
    levelClear: "Clear",
    boardLabel: { Edexcel: "Edexcel / EDX", CIE: "Cambridge / CIE" },
    boardShort: { Edexcel: "EDX", CIE: "CIE" },
    cieIncludeAll: "Checking this includes all papers under this subject",
    paperCount: (count) => `${count} papers`,
    ciePaperSummary: (count, paperTypes) => `${count} papers: ${paperTypes}`,
    moreTypes: (count) => `+${count} more`,
    paperType: {
      multiple: "Multiple Choice",
      structure: "Structured",
      experiment: "Experiment",
      reading: "Reading",
      writing: "Writing",
      readingWriting: "Reading/Writing",
      listening: "Listening",
      speaking: "Speaking",
      literature: "Literature",
      essayData: "Essay/Data",
      coursework: "Coursework",
      pureMath: "Pure Math",
      mechanics: "Mechanics",
      statistics: "Statistics",
    },
    paperJoiner: " + ",
    noSelection: "No exams selected yet.",
    needSelection: "Please select at least 1 exam.",
    unresolvedStatus: (count) => `Calendar generated, but ${count} conflict group(s) still need manual confirmation.`,
    generatedStatus: "Calendar generated. You can export PNG or ICS now.",
    noDisplay: "No events to display.",
    summaryLabel: {
      examCount: "Exam Count",
      autoAdjusted: "Auto-adjusted Sessions",
      supervisedBreak: "Supervised Break",
      dateRange: "Date Range",
      initialConflicts: "Initial Conflicts",
    },
    warningAdjusted: "Auto-switched to S2/S3:",
    warningUnresolved: "Still unresolved conflicts:",
    breakTitle: "Supervised Break",
    minuteUnit: "minutes",
    notePrefix: "Note",
    exportPngNeed: "Please generate calendar before exporting PNG.",
    exportPngMissingLib: "PNG export failed: html2canvas is unavailable.",
    exportPngBlobFail: "PNG export failed: unable to build image blob.",
    exportPngSuccess: "PNG exported successfully.",
    exportPngFail: "PNG export failed. Please try again.",
    exportIcsNeed: "Please generate calendar before exporting ICS.",
    exportIcsSuccessWithAlerts: "ICS exported successfully (with reminders).",
    exportIcsSuccessNoAlerts: "ICS exported successfully (without reminders).",
    reminderTomorrow: (code) => `Reminder: ${code} tomorrow`,
    reminderTwoHours: (code) => `Reminder: ${code} in 2 hours`,
    imgTitle: "2026 Exam Timetable",
    imgSubtitle: "June 2026 Personal Exam Plan",
    imgExamCount: (count) => `${count} Exams`,
    imgThDate: "Date",
    imgThTime: "Time",
    imgThSubject: "Subject / Unit",
    imgThVenue: "Venue",
    imgArrival: "Arrive by",
    imgFooter: "Generated by 2026 Exam Calendar Tool",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
};

const state = {
  payload: null,
  selectedIds: new Set(),
  searchText: "",
  activeLevelFilter: "ALL",
  visibleIds: new Set(),
  visibleByLevel: new Map(),
  subjectIdMap: new Map(),
  generated: null,
  lang: "zh",
  includeAlerts: true,
};

const dom = {
  langToggleBtn: document.getElementById("langToggleBtn"),
  langBtnText: document.getElementById("langBtnText"),
  headerTitle: document.getElementById("headerTitle"),
  headerSubtitle: document.getElementById("headerSubtitle"),
  revisionLabel: document.getElementById("revisionLabel"),
  pickerTitle: document.getElementById("pickerTitle"),
  searchLabel: document.getElementById("searchLabel"),
  searchInput: document.getElementById("searchInput"),
  levelFilter: document.getElementById("levelFilter"),
  selectVisibleBtn: document.getElementById("selectVisibleBtn"),
  clearVisibleBtn: document.getElementById("clearVisibleBtn"),
  generateBtn: document.getElementById("generateBtn"),
  pickerStats: document.getElementById("pickerStats"),
  examPicker: document.getElementById("examPicker"),
  previewTitle: document.getElementById("previewTitle"),
  statusMessage: document.getElementById("statusMessage"),
  alertToggle: document.getElementById("alertToggle"),
  alertToggleLabel: document.getElementById("alertToggleLabel"),
  exportPngBtn: document.getElementById("exportPngBtn"),
  exportIcsBtn: document.getElementById("exportIcsBtn"),
  printCard: document.getElementById("printCard"),
  cardTitle: document.getElementById("cardTitle"),
  summaryBlock: document.getElementById("summaryBlock"),
  warningBlock: document.getElementById("warningBlock"),
  timelineList: document.getElementById("timelineList"),
  footerText: document.getElementById("footerText"),
  imageExportContainer: document.getElementById("imageExportContainer"),
  imgTitle: document.getElementById("imgTitle"),
  imgSubtitle: document.getElementById("imgSubtitle"),
  imgExamCount: document.getElementById("imgExamCount"),
  imgThDate: document.getElementById("imgThDate"),
  imgThTime: document.getElementById("imgThTime"),
  imgThSubject: document.getElementById("imgThSubject"),
  imgThVenue: document.getElementById("imgThVenue"),
  imgTableBody: document.getElementById("imgTableBody"),
  imgFooter: document.getElementById("imgFooter"),
};

void init();

function getText() {
  return I18N[state.lang];
}

async function init() {
  bindEvents();
  applyLanguage();
  setStatus(getText().loadingData);
  renderEmptyCard(getText().selectPrompt);

  try {
    const response = await fetch(DATA_URL, { cache: "no-store" });
    if (!response.ok) {
      throw new Error(`load-failed: ${response.status}`);
    }
    state.payload = await response.json();
    renderLevelFilter();
    renderPicker();
    const range = state.payload.meta.dateRange;
    setStatus(getText().loadedRange(state.payload.meta.totalExamFamilies, range.start, range.end));
  } catch (error) {
    console.error(error);
    setStatus(getText().loadFailed);
    renderEmptyCard(getText().loadFailed);
  }
}

function bindEvents() {
  dom.langToggleBtn.addEventListener("click", () => {
    state.lang = state.lang === "zh" ? "en" : "zh";
    applyLanguage();
    renderPicker();
    if (state.selectedIds.size > 0) {
      generatePersonalCalendar(false);
    } else if (state.payload) {
      const range = state.payload.meta.dateRange;
      setStatus(getText().loadedRange(state.payload.meta.totalExamFamilies, range.start, range.end));
      renderEmptyCard(getText().selectPrompt);
    }
  });

  dom.searchInput.addEventListener("input", (event) => {
    state.searchText = event.target.value.trim().toLowerCase();
    renderPicker();
  });

  dom.levelFilter.addEventListener("click", (event) => {
    const target = event.target;
    if (!(target instanceof HTMLElement)) {
      return;
    }
    const button = target.closest("button[data-level-filter]");
    if (!button) {
      return;
    }
    const next = button.dataset.levelFilter;
    if (!next || next === state.activeLevelFilter) {
      return;
    }
    state.activeLevelFilter = next;
    renderLevelFilter();
    renderPicker();
  });

  dom.selectVisibleBtn.addEventListener("click", () => {
    updateIdsSelection(Array.from(state.visibleIds), true);
  });

  dom.clearVisibleBtn.addEventListener("click", () => {
    updateIdsSelection(Array.from(state.visibleIds), false);
  });

  dom.generateBtn.addEventListener("click", () => {
    generatePersonalCalendar();
  });

  dom.alertToggle.addEventListener("change", () => {
    state.includeAlerts = dom.alertToggle.checked;
  });

  dom.exportPngBtn.addEventListener("click", () => {
    void exportAsPng();
  });

  dom.exportIcsBtn.addEventListener("click", () => {
    exportAsIcs();
  });

  dom.examPicker.addEventListener("change", (event) => {
    const target = event.target;
    if (!(target instanceof HTMLInputElement)) {
      return;
    }

    const subjectKey = target.dataset.subjectKey;
    if (subjectKey) {
      const ids = state.subjectIdMap.get(subjectKey) || [];
      updateIdsSelection(ids, target.checked);
      return;
    }

    const familyId = target.dataset.familyId;
    if (!familyId) {
      return;
    }

    if (target.checked) {
      state.selectedIds.add(familyId);
    } else {
      state.selectedIds.delete(familyId);
    }

    normalizeCieSelection();
    renderPicker();
    generatePersonalCalendar(false);
  });

  dom.examPicker.addEventListener("click", (event) => {
    const target = event.target;
    if (!(target instanceof HTMLElement)) {
      return;
    }
    const actionButton = target.closest("button[data-action]");
    if (!actionButton) {
      return;
    }
    const action = actionButton.dataset.action;
    if (action !== "select-level" && action !== "clear-level") {
      return;
    }
    const level = actionButton.dataset.level;
    if (!level) {
      return;
    }
    const ids = state.visibleByLevel.get(level) || [];
    updateIdsSelection(ids, action === "select-level");
  });
}

function applyLanguage() {
  const t = getText();
  document.documentElement.lang = state.lang === "zh" ? "zh-CN" : "en";
  dom.langBtnText.textContent = t.langButton;
  dom.headerTitle.textContent = t.headerTitle;
  dom.headerSubtitle.textContent = t.headerSubtitle;
  dom.revisionLabel.textContent = t.revisionLabel;
  dom.pickerTitle.textContent = t.pickerTitle;
  dom.searchLabel.textContent = t.searchLabel;
  dom.searchInput.placeholder = t.searchPlaceholder;
  dom.selectVisibleBtn.textContent = t.actionSelectVisible;
  dom.clearVisibleBtn.textContent = t.actionClearVisible;
  dom.generateBtn.textContent = t.actionManualRefresh;
  dom.previewTitle.textContent = t.previewTitle;
  dom.alertToggleLabel.textContent = t.alertToggleLabel;
  dom.exportPngBtn.textContent = t.exportPng;
  dom.exportIcsBtn.textContent = t.exportIcs;
  dom.cardTitle.textContent = t.cardTitle;
  dom.footerText.textContent = t.footerText;
  dom.imgTitle.textContent = t.imgTitle;
  dom.imgSubtitle.textContent = t.imgSubtitle;
  dom.imgExamCount.textContent = t.imgExamCount(0);
  dom.imgThDate.textContent = t.imgThDate;
  dom.imgThTime.textContent = t.imgThTime;
  dom.imgThSubject.textContent = t.imgThSubject;
  dom.imgThVenue.textContent = t.imgThVenue;
  dom.imgFooter.textContent = t.imgFooter;
  renderLevelFilter();
}

function renderLevelFilter() {
  const t = getText();
  const chips = dom.levelFilter.querySelectorAll("button[data-level-filter]");
  for (const chip of chips) {
    if (!(chip instanceof HTMLButtonElement)) {
      continue;
    }
    const key = chip.dataset.levelFilter || "ALL";
    chip.textContent = t.levelFilter[key] || key;
    const isActive = key === state.activeLevelFilter;
    chip.classList.toggle("is-active", isActive);
    chip.setAttribute("aria-selected", isActive ? "true" : "false");
  }
}

function renderPicker() {
  if (!state.payload) {
    return;
  }

  const t = getText();
  const families = state.payload.examFamilies
    .filter((family) => matchesSearch(family, state.searchText))
    .filter((family) => state.activeLevelFilter === "ALL" || family.level === state.activeLevelFilter);

  state.visibleIds = new Set(families.map((item) => item.id));
  state.visibleByLevel = new Map();
  state.subjectIdMap = new Map();

  if (!families.length) {
    dom.examPicker.innerHTML = `<div class="empty-state">${escapeHtml(t.noResults)}</div>`;
    refreshSelectionStatus();
    return;
  }

  const sections = [];
  for (const level of state.payload.meta.levels) {
    if (state.activeLevelFilter !== "ALL" && state.activeLevelFilter !== level) {
      continue;
    }

    const levelFamilies = families.filter((item) => item.level === level);
    if (!levelFamilies.length) {
      continue;
    }

    state.visibleByLevel.set(
      level,
      levelFamilies.map((item) => item.id)
    );

    const boardBlocks = BOARD_ORDER.map((board) => {
      const boardFamilies = levelFamilies.filter((item) => item.board === board);
      if (!boardFamilies.length) {
        return "";
      }

      const cards = board === "CIE" ? renderCieCards(level, boardFamilies) : renderEdexcelCards(boardFamilies);
      return `
        <section class="board-section board-${escapeHtml(board.toLowerCase())}">
          <div class="board-head">
            <h4 class="board-title">${escapeHtml(t.boardLabel[board] || board)}</h4>
            <span class="board-count">${escapeHtml(t.levelCount(boardFamilies.length))}</span>
          </div>
          <div class="card-grid">${cards.join("")}</div>
        </section>
      `;
    })
      .filter(Boolean)
      .join("");

    sections.push(`
      <section class="level-section level-${level}">
        <div class="level-head">
          <div>
            <h3 class="level-title">${escapeHtml(t.levelLabel[level] || level)}</h3>
            <div class="level-meta">${escapeHtml(t.levelCount(levelFamilies.length))}</div>
          </div>
          <div class="level-actions">
            <button class="level-btn" type="button" data-action="select-level" data-level="${level}">${escapeHtml(
      t.levelSelect
    )}</button>
            <button class="level-btn" type="button" data-action="clear-level" data-level="${level}">${escapeHtml(
      t.levelClear
    )}</button>
          </div>
        </div>
        ${boardBlocks}
      </section>
    `);
  }

  dom.examPicker.innerHTML = sections.join("");
  refreshSelectionStatus();
}

function renderEdexcelCards(families) {
  const t = getText();
  return [...families]
    .sort((left, right) => {
      const subjectDiff = left.subject.localeCompare(right.subject, "en", { sensitivity: "base" });
      if (subjectDiff !== 0) {
        return subjectDiff;
      }
      return left.code.localeCompare(right.code, "en", { sensitivity: "base" });
    })
    .map((family) => {
      const selected = state.selectedIds.has(family.id);
      const first = family.variants[0];
      const boardCode = `${t.boardShort[family.board] || family.board}: ${family.code}`;
      const subjectShort = buildIcsSubjectShort(family);
      const cardTitle = subjectShort ? `${family.subject} ${subjectShort}` : family.subject;
      const cardClass = selected ? "exam-card selected edx-card" : "exam-card edx-card";
      return `
        <label class="${cardClass}">
          <input class="card-check" type="checkbox" data-family-id="${escapeHtml(family.id)}" ${
            selected ? "checked" : ""
          } />
          <div class="card-top">
            <span class="card-code">${escapeHtml(boardCode)}</span>
          </div>
          <div class="card-title">${escapeHtml(cardTitle)}</div>
          <div class="card-sub">${escapeHtml(family.paper)}</div>
          <div class="card-date">${escapeHtml(formatDateLabel(first.date))}</div>
        </label>
      `;
    });
}

function renderCieCards(level, families) {
  const t = getText();
  const groups = groupFamiliesBySubject(families);
  return groups.map((group) => {
    const subjectKey = encodeURIComponent(`${level}|${group.board}|${group.subject}`);
    const groupIds = group.families.map((item) => item.id);
    state.subjectIdMap.set(subjectKey, groupIds);
    const selected = groupIds.every((id) => state.selectedIds.has(id));
    const boardCode = `${t.boardShort[group.board] || group.board}: ${getCieSyllabusCode(group.families)}`;
    const firstDate = getEarliestVariantDate(group.families);
    const summary = buildCiePaperSummary(group.families);
    const cardClass = selected ? "exam-card selected cie-card" : "exam-card cie-card";
    return `
      <label class="${cardClass}">
        <input class="card-check" type="checkbox" data-subject-key="${subjectKey}" ${selected ? "checked" : ""} />
        <div class="card-top">
          <span class="card-code">${escapeHtml(boardCode)}</span>
          <span class="card-tag">${escapeHtml(t.paperCount(group.families.length))}</span>
        </div>
        <div class="card-title">${escapeHtml(group.subject)}</div>
        <div class="card-sub">${escapeHtml(summary)}</div>
        <div class="card-date">${escapeHtml(formatDateLabel(firstDate))}</div>
      </label>
    `;
  });
}

function groupFamiliesBySubject(families) {
  const map = new Map();
  for (const family of families) {
    const groupSubject = buildCieSubjectGroupName(family);
    const key = `${family.board}|${groupSubject}`;
    if (!map.has(key)) {
      map.set(key, { board: family.board, subject: groupSubject, families: [] });
    }
    map.get(key).families.push(family);
  }

  return Array.from(map.values())
    .map((group) => {
      group.families.sort((left, right) => left.code.localeCompare(right.code, "en", { sensitivity: "base" }));
      return group;
    })
    .sort((left, right) => left.subject.localeCompare(right.subject, "en", { sensitivity: "base" }));
}

function buildCieSubjectGroupName(family) {
  const subject = family.subject;
  const paper = String(family.paper || "");
  if (/mathematics/i.test(subject)) {
    if (/\bcore\b/i.test(paper)) {
      return "Mathematics (Core)";
    }
    if (/\bextended\b/i.test(paper)) {
      return "Mathematics (Extended)";
    }
  }
  return subject;
}

function getCieSelectionKey(family) {
  return `${family.level}|${buildCieSubjectGroupName(family)}`;
}

function getCieSyllabusCode(families) {
  const codeSet = new Set(
    families.map((family) => {
      const parts = String(family.code).split("/");
      return parts[0] || family.code;
    })
  );
  return Array.from(codeSet).join("/");
}

function getEarliestVariantDate(families) {
  const dates = families
    .flatMap((family) => family.variants.map((variant) => variant.date))
    .sort((left, right) => left.localeCompare(right));
  return dates[0] || "";
}

function buildCiePaperSummary(families) {
  const t = getText();
  const types = [];
  for (const family of families) {
    const label = classifyCiePaperLabel(family.paper);
    if (!types.includes(label)) {
      types.push(label);
    }
  }
  const shown = types.slice(0, 4);
  if (types.length > 4) {
    shown.push(t.moreTypes(types.length - 4));
  }
  return t.ciePaperSummary(families.length, shown.join(t.paperJoiner));
}

function classifyCiePaperLabel(paper) {
  const text = paper.toLowerCase();
  const k = getText().paperType;

  if (text.includes("multiple choice")) {
    return k.multiple;
  }
  if (text.includes("alternative to practical") || text.includes("practical")) {
    return k.experiment;
  }
  if (text.includes("theory") || text.includes("structured questions") || text.includes("structured")) {
    return k.structure;
  }
  if (text.includes("reading and writing") || text.includes("reading, directed writing")) {
    return k.readingWriting;
  }
  if (text.includes("reading")) {
    return k.reading;
  }
  if (text.includes("writing")) {
    return k.writing;
  }
  if (text.includes("listening")) {
    return k.listening;
  }
  if (text.includes("speaking") || text.includes("oral")) {
    return k.speaking;
  }
  if (text.includes("poetry") || text.includes("prose") || text.includes("literature") || text.includes("drama")) {
    return k.literature;
  }
  if (
    text.includes("essay") ||
    text.includes("data response") ||
    text.includes("research methods") ||
    text.includes("issues and debates") ||
    text.includes("planning, analysis")
  ) {
    return k.essayData;
  }
  if (text.includes("coursework")) {
    return k.coursework;
  }
  if (text.includes("pure mathematics")) {
    return k.pureMath;
  }
  if (text.includes("mechanics")) {
    return k.mechanics;
  }
  if (text.includes("statistics") || text.includes("probability")) {
    return k.statistics;
  }

  return cleanupPaperLabel(paper);
}

function cleanupPaperLabel(paper) {
  return String(paper)
    .replace(/\s*\(?\d{2}\)?$/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function matchesSearch(family, searchText) {
  if (!searchText) {
    return true;
  }
  const haystack = [
    family.level,
    family.board,
    family.board === "Edexcel" ? "edx" : "",
    family.qualification,
    family.subject,
    family.code,
    family.paper,
    ...family.variants.map((variant) => `${variant.session} ${variant.date}`),
  ]
    .join(" ")
    .toLowerCase();
  return haystack.includes(searchText);
}

function updateIdsSelection(ids, checked) {
  for (const id of ids) {
    if (checked) {
      state.selectedIds.add(id);
    } else {
      state.selectedIds.delete(id);
    }
  }
  normalizeCieSelection();
  renderPicker();
  generatePersonalCalendar(false);
}

function normalizeCieSelection() {
  if (!state.payload) {
    return;
  }
  const cieSubjectMap = new Map();
  for (const family of state.payload.examFamilies) {
    if (family.board !== "CIE") {
      continue;
    }
    const key = getCieSelectionKey(family);
    if (!cieSubjectMap.has(key)) {
      cieSubjectMap.set(key, []);
    }
    cieSubjectMap.get(key).push(family.id);
  }
  for (const ids of cieSubjectMap.values()) {
    const selectedCount = ids.filter((id) => state.selectedIds.has(id)).length;
    if (selectedCount > 0 && selectedCount < ids.length) {
      for (const id of ids) {
        state.selectedIds.add(id);
      }
    }
  }
}

function refreshSelectionStatus() {
  if (!state.payload) {
    return;
  }
  const t = getText();
  const total = state.payload.examFamilies.length;
  const selected = state.selectedIds.size;
  const visible = state.visibleIds.size;
  const selectedVisible = Array.from(state.visibleIds).filter((id) => state.selectedIds.has(id)).length;
  dom.pickerStats.textContent = t.stats(selected, total, visible, selectedVisible);
}

function generatePersonalCalendar(showStatus = true) {
  if (!state.payload) {
    return;
  }

  const t = getText();
  const selectedFamilies = state.payload.examFamilies.filter((family) => state.selectedIds.has(family.id));
  if (!selectedFamilies.length) {
    state.generated = null;
    renderEmptyCard(t.noSelection);
    dom.exportPngBtn.disabled = true;
    dom.exportIcsBtn.disabled = true;
    if (showStatus) {
      setStatus(t.needSelection);
    }
    return;
  }

  state.generated = buildPersonalSchedule(selectedFamilies);
  renderGeneratedCard();
  dom.exportPngBtn.disabled = false;
  dom.exportIcsBtn.disabled = false;

  if (showStatus) {
    const unresolvedCount = state.generated.unresolvedPairs.length;
    if (unresolvedCount > 0) {
      setStatus(t.unresolvedStatus(unresolvedCount));
    } else {
      setStatus(t.generatedStatus);
    }
  }
}

function buildPersonalSchedule(families) {
  const assignments = new Map(families.map((family) => [family.id, 0]));
  const moveLog = [];
  const initialEvents = buildEvents(families, assignments).sort(compareByDateTime);
  const initialConflictCount = findConflicts(initialEvents).length;
  const maxRounds = families.length * 8;

  for (let round = 0; round < maxRounds; round += 1) {
    const events = buildEvents(families, assignments).sort(compareByDateTime);
    const conflicts = findConflicts(events);
    if (!conflicts.length) {
      break;
    }

    let moved = false;
    for (const [leftIndex, rightIndex] of conflicts) {
      const left = events[leftIndex];
      const right = events[rightIndex];
      const move = chooseConflictMove(left, right, events);
      if (!move) {
        continue;
      }
      assignments.set(move.familyId, move.nextIndex);
      moveLog.push(move);
      moved = true;
    }

    if (!moved) {
      break;
    }
  }

  const finalEvents = buildEvents(families, assignments).sort(compareByDateTime);
  const unresolvedPairs = findConflicts(finalEvents).map(([leftIndex, rightIndex]) => {
    const left = finalEvents[leftIndex];
    const right = finalEvents[rightIndex];
    return `${left.code} (${left.session}) × ${right.code} (${right.session}) @ ${left.date}`;
  });

  const adjustments = finalEvents
    .filter((event) => event.adjusted)
    .map((event) => ({
      familyId: event.familyId,
      code: event.code,
      fromSession: "S1",
      toSession: event.session,
      date: event.date,
      start: event.start,
      end: event.end,
    }));

  const breakEvents = buildSupervisedBreaks(finalEvents, moveLog, adjustments);
  return {
    examEvents: finalEvents,
    breakEvents,
    adjustments,
    unresolvedPairs,
    initialConflictCount,
  };
}

function buildEvents(families, assignments) {
  return families.map((family) => {
    const index = assignments.get(family.id) || 0;
    return createEventFromFamily(family, index);
  });
}

function createEventFromFamily(family, variantIndex) {
  const variant = family.variants[variantIndex];
  return {
    type: "exam",
    familyId: family.id,
    family,
    variantIndex,
    adjusted: variantIndex > 0,
    level: family.level,
    board: family.board,
    subject: family.subject,
    code: family.code,
    paper: family.paper,
    session: variant.session,
    date: variant.date,
    start: variant.start,
    end: variant.end,
    startMinutes: variant.startMinutes,
    endMinutes: variant.endMinutes,
    durationMinutes: variant.durationMinutes,
    fullSupervisionRequired: variant.fullSupervisionRequired,
    note: variant.note,
    venue: variant.venue,
    arrival: variant.arrival,
  };
}

function findConflicts(events) {
  const conflicts = [];
  for (let i = 0; i < events.length; i += 1) {
    for (let j = i + 1; j < events.length; j += 1) {
      if (isOverlapped(events[i], events[j])) {
        conflicts.push([i, j]);
      }
    }
  }
  return conflicts;
}

function isOverlapped(left, right) {
  if (left.date !== right.date) {
    return false;
  }
  return left.startMinutes < right.endMinutes && right.startMinutes < left.endMinutes;
}

function chooseConflictMove(left, right, allEvents) {
  const options = [];
  const nextLeft = findNextVariantIndex(left, allEvents);
  if (nextLeft >= 0) {
    options.push(buildMoveOption(left, right, nextLeft));
  }
  const nextRight = findNextVariantIndex(right, allEvents);
  if (nextRight >= 0) {
    options.push(buildMoveOption(right, left, nextRight));
  }
  if (!options.length) {
    return null;
  }
  options.sort((a, b) => {
    if (a.targetSessionRank !== b.targetSessionRank) {
      return a.targetSessionRank - b.targetSessionRank;
    }
    if (a.shiftSteps !== b.shiftSteps) {
      return a.shiftSteps - b.shiftSteps;
    }
    return a.targetStartMinutes - b.targetStartMinutes;
  });
  return options[0];
}

function buildMoveOption(movedEvent, otherEvent, nextIndex) {
  const nextVariant = movedEvent.family.variants[nextIndex];
  return {
    familyId: movedEvent.familyId,
    otherId: otherEvent.familyId,
    nextIndex,
    fromSession: movedEvent.session,
    toSession: nextVariant.session,
    shiftSteps: nextIndex - movedEvent.variantIndex,
    targetSessionRank: getSessionRank(nextVariant.session),
    targetStartMinutes: nextVariant.startMinutes,
  };
}

function findNextVariantIndex(targetEvent, allEvents) {
  const family = targetEvent.family;
  for (let index = targetEvent.variantIndex + 1; index < family.variants.length; index += 1) {
    const candidate = createEventFromFamily(family, index);
    const hasConflict = allEvents.some((event) => {
      if (event.familyId === targetEvent.familyId) {
        return false;
      }
      return isOverlapped(candidate, event);
    });
    if (!hasConflict) {
      return index;
    }
  }
  return -1;
}

function buildSupervisedBreaks(examEvents, moveLog, adjustments) {
  const byId = new Map(examEvents.map((event) => [event.familyId, event]));
  const breaks = [];
  const usedKeys = new Set();

  const addBreak = (firstEvent, secondEvent, source) => {
    if (!firstEvent || !secondEvent || firstEvent.date !== secondEvent.date) {
      return;
    }
    const earlier = firstEvent.startMinutes <= secondEvent.startMinutes ? firstEvent : secondEvent;
    const later = earlier === firstEvent ? secondEvent : firstEvent;
    const gap = later.startMinutes - earlier.endMinutes;
    if (gap <= 0) {
      return;
    }
    const key = `${earlier.date}|${earlier.endMinutes}|${later.startMinutes}`;
    if (usedKeys.has(key)) {
      return;
    }
    usedKeys.add(key);
    breaks.push({
      type: "break",
      date: earlier.date,
      startMinutes: earlier.endMinutes,
      endMinutes: later.startMinutes,
      start: minutesToHHMM(earlier.endMinutes),
      end: minutesToHHMM(later.startMinutes),
      durationMinutes: gap,
      source,
      leftCode: earlier.code,
      rightCode: later.code,
    });
  };

  for (const item of moveLog) {
    addBreak(byId.get(item.familyId), byId.get(item.otherId), `${item.fromSession}->${item.toSession}`);
  }

  if (!breaks.length) {
    for (const adjustment of adjustments) {
      const event = byId.get(adjustment.familyId);
      if (!event) {
        continue;
      }
      const previous = examEvents
        .filter(
          (candidate) =>
            candidate.date === event.date &&
            candidate.familyId !== event.familyId &&
            candidate.endMinutes <= event.startMinutes
        )
        .sort((a, b) => b.endMinutes - a.endMinutes)[0];
      if (previous) {
        addBreak(previous, event, `auto-${event.session}`);
      }
    }
  }

  return breaks.sort(compareByDateTime);
}

function compareByDateTime(left, right) {
  if (left.date !== right.date) {
    return left.date.localeCompare(right.date);
  }
  if (left.startMinutes !== right.startMinutes) {
    return left.startMinutes - right.startMinutes;
  }
  return (left.endMinutes || 0) - (right.endMinutes || 0);
}

function renderGeneratedCard() {
  if (!state.generated) {
    return;
  }
  const t = getText();
  const { examEvents, breakEvents, adjustments, unresolvedPairs, initialConflictCount } = state.generated;
  if (!examEvents.length) {
    renderEmptyCard(t.noDisplay);
    return;
  }

  const allItems = [...examEvents, ...breakEvents].sort(compareByDateTime);
  const firstDate = examEvents[0].date;
  const lastDate = examEvents[examEvents.length - 1].date;
  const s = t.summaryLabel;

  dom.summaryBlock.innerHTML = `
    <div><strong>${escapeHtml(s.examCount)}:</strong> ${examEvents.length}</div>
    <div><strong>${escapeHtml(s.autoAdjusted)}:</strong> ${adjustments.length}</div>
    <div><strong>${escapeHtml(s.supervisedBreak)}:</strong> ${breakEvents.length}</div>
    <div><strong>${escapeHtml(s.dateRange)}:</strong> ${escapeHtml(firstDate)} → ${escapeHtml(lastDate)}</div>
    <div><strong>${escapeHtml(s.initialConflicts)}:</strong> ${initialConflictCount}</div>
  `;

  const warningParts = [];
  if (adjustments.length) {
    const adjustmentText = adjustments
      .slice(0, 8)
      .map((item) => `${item.code} ${item.date} ${item.fromSession} → ${item.toSession} (${item.start}-${item.end})`)
      .join("<br />");
    warningParts.push(`<div><strong>${escapeHtml(t.warningAdjusted)}</strong><br />${adjustmentText}</div>`);
  }
  if (unresolvedPairs.length) {
    const unresolvedText = unresolvedPairs
      .slice(0, 8)
      .map((item) => escapeHtml(item))
      .join("<br />");
    warningParts.push(`<div><strong>${escapeHtml(t.warningUnresolved)}</strong><br />${unresolvedText}</div>`);
  }
  dom.warningBlock.innerHTML = warningParts.length ? warningParts.join("<hr />") : "";

  const rows = allItems
    .map((item, index) => {
      if (item.type === "break") {
        return `
          <li class="timeline-item break-item" style="animation-delay:${Math.min(index * 30, 320)}ms">
            <div class="timeline-head">
              <span>${escapeHtml(formatDateLabel(item.date))}</span>
              <span>${escapeHtml(item.start)}-${escapeHtml(item.end)}</span>
            </div>
            <div class="timeline-title"><strong>${escapeHtml(t.breakTitle)}</strong> · ${item.durationMinutes} ${escapeHtml(
          t.minuteUnit
        )}</div>
            <div class="timeline-meta">${escapeHtml(item.leftCode)} → ${escapeHtml(item.rightCode)}</div>
          </li>
        `;
      }

      const noteText = item.note ? ` · ${escapeHtml(t.notePrefix)}: ${escapeHtml(item.note)}` : "";
      const adjusted = item.adjusted ? ` · <strong>${escapeHtml(item.session)}</strong>` : ` · ${escapeHtml(item.session)}`;
      return `
        <li class="timeline-item" style="animation-delay:${Math.min(index * 30, 320)}ms">
          <div class="timeline-head">
            <span>${escapeHtml(formatDateLabel(item.date))}</span>
            <span>${escapeHtml(item.start)}-${escapeHtml(item.end)}</span>
          </div>
          <div class="timeline-title"><strong>${escapeHtml(item.code)}</strong> ${escapeHtml(item.paper)}</div>
          <div class="timeline-meta">${escapeHtml(item.board)} · ${escapeHtml(item.level)} · ${escapeHtml(
        item.subject
      )}${adjusted}${noteText}</div>
        </li>
      `;
    })
    .join("");

  dom.timelineList.innerHTML = rows;
}

function renderEmptyCard(text) {
  dom.summaryBlock.innerHTML = "";
  dom.warningBlock.innerHTML = "";
  dom.timelineList.innerHTML = `<li class="empty-state">${escapeHtml(text)}</li>`;
}

function renderImageExport() {
  const t = getText();
  dom.imgTitle.textContent = t.imgTitle;
  dom.imgSubtitle.textContent = t.imgSubtitle;
  dom.imgThDate.textContent = t.imgThDate;
  dom.imgThTime.textContent = t.imgThTime;
  dom.imgThSubject.textContent = t.imgThSubject;
  dom.imgThVenue.textContent = t.imgThVenue;
  dom.imgFooter.textContent = t.imgFooter;

  if (!state.generated || !state.generated.examEvents.length) {
    dom.imgExamCount.textContent = t.imgExamCount(0);
    dom.imgTableBody.innerHTML = "";
    return;
  }

  const examEvents = [...state.generated.examEvents].sort(compareByDateTime);
  dom.imgExamCount.textContent = t.imgExamCount(examEvents.length);
  dom.imgTableBody.innerHTML = examEvents
    .map((event) => {
      const arrivalLine = event.arrival
        ? `<div class="img-arrival">${escapeHtml(t.imgArrival)}: ${escapeHtml(event.arrival)}</div>`
        : "";
      const venueNote = formatImageVenueNote(event.note);
      const noteLine = venueNote ? `<div class="img-note">${escapeHtml(venueNote)}</div>` : "";
      return `
        <tr>
          <td>${escapeHtml(event.date)}</td>
          <td>
            <div class="img-time">${escapeHtml(event.start)} - ${escapeHtml(event.end)}</div>
            ${arrivalLine}
          </td>
          <td>
            <div class="img-code">${escapeHtml(getBoardShort(event.board))}: ${escapeHtml(event.code)}</div>
            <div class="img-subject">${escapeHtml(event.subject)}</div>
            <div class="img-paper">${escapeHtml(event.paper)}</div>
          </td>
          <td>
            <div class="img-venue">${escapeHtml(event.venue || "-")}</div>
            ${noteLine}
          </td>
        </tr>
      `;
    })
    .join("");
}

async function exportAsPng() {
  const t = getText();
  if (!state.generated || !state.generated.examEvents.length) {
    setStatus(t.exportPngNeed);
    return;
  }
  if (typeof window.html2canvas !== "function") {
    setStatus(t.exportPngMissingLib);
    return;
  }

  renderImageExport();
  dom.imageExportContainer.classList.add("for-capture");

  try {
    const canvas = await window.html2canvas(dom.imageExportContainer, {
      scale: 2,
      backgroundColor: "#eef2ff",
      useCORS: true,
      scrollX: 0,
      scrollY: 0,
      windowWidth: 1240,
    });
    canvas.toBlob((blob) => {
      if (!blob) {
        setStatus(t.exportPngBlobFail);
        return;
      }
      downloadBlob("exam-calendar-2026-june.png", blob);
      setStatus(t.exportPngSuccess);
    }, "image/png");
  } catch (error) {
    console.error(error);
    setStatus(t.exportPngFail);
  } finally {
    dom.imageExportContainer.classList.remove("for-capture");
  }
}

function exportAsIcs() {
  const t = getText();
  if (!state.generated || !state.generated.examEvents.length) {
    setStatus(t.exportIcsNeed);
    return;
  }
  const content = buildIcsContent(state.generated, state.includeAlerts);
  const blob = new Blob([content], { type: "text/calendar;charset=utf-8" });
  downloadBlob("exam-calendar-2026-june.ics", blob);
  setStatus(state.includeAlerts ? t.exportIcsSuccessWithAlerts : t.exportIcsSuccessNoAlerts);
}

function buildIcsContent(generated, includeAlerts) {
  const t = getText();
  const lines = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Exam Calendar Generator//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "X-WR-CALNAME:Personal Exam Calendar",
    "X-WR-TIMEZONE:Asia/Shanghai",
    "BEGIN:VTIMEZONE",
    "TZID:Asia/Shanghai",
    "BEGIN:STANDARD",
    "TZOFFSETFROM:+0800",
    "TZOFFSETTO:+0800",
    "TZNAME:CST",
    "DTSTART:19700101T000000",
    "END:STANDARD",
    "END:VTIMEZONE",
  ];

  const stamp = formatUtcStamp(new Date());
  for (const event of generated.examEvents) {
    const uid = `${event.familyId}-${event.date}-${event.session}@exam-calendar`;
    const subjectShort = buildIcsSubjectShort(event);
    const summary = subjectShort ? `${event.subject} ${subjectShort}` : `${event.subject} ${event.code}`;
    const description = [
      `Exam Code: ${event.code}`,
      `Subject: ${summary}`,
      `Full Name: ${event.paper}`,
      `Room: ${event.venue || "TBC"}`,
      event.arrival ? `Arrive: ${event.arrival}` : "",
      `Board: ${event.board}`,
      `Level: ${event.level}`,
      `Session: ${event.session}`,
      event.fullSupervisionRequired ? "Supervision: Full supervision required" : "",
      event.note ? `Note: ${event.note}` : "",
    ]
      .filter(Boolean)
      .join("\n");

    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${escapeIcs(uid)}`);
    lines.push(`DTSTAMP:${stamp}`);
    lines.push(`DTSTART;TZID=Asia/Shanghai:${formatIcsDateTime(event.date, event.start)}`);
    lines.push(`DTEND;TZID=Asia/Shanghai:${formatIcsDateTime(event.date, event.end)}`);
    lines.push(`SUMMARY:${escapeIcs(summary)}`);
    if (event.venue) {
      lines.push(`LOCATION:${escapeIcs(event.venue)}`);
    }
    lines.push(`DESCRIPTION:${escapeIcs(description)}`);

    if (includeAlerts) {
      lines.push("BEGIN:VALARM");
      lines.push("ACTION:DISPLAY");
      lines.push("TRIGGER:-P1D");
      lines.push(`DESCRIPTION:${escapeIcs(t.reminderTomorrow(event.code))}`);
      lines.push("END:VALARM");

      lines.push("BEGIN:VALARM");
      lines.push("ACTION:DISPLAY");
      lines.push("TRIGGER:-PT2H");
      lines.push(`DESCRIPTION:${escapeIcs(t.reminderTwoHours(event.code))}`);
      lines.push("END:VALARM");
    }

    lines.push("END:VEVENT");
  }

  for (const event of generated.breakEvents) {
    const uid = `break-${event.date}-${event.start}-${event.end}@exam-calendar`;
    lines.push("BEGIN:VEVENT");
    lines.push(`UID:${escapeIcs(uid)}`);
    lines.push(`DTSTAMP:${stamp}`);
    lines.push(`DTSTART;TZID=Asia/Shanghai:${formatIcsDateTime(event.date, event.start)}`);
    lines.push(`DTEND;TZID=Asia/Shanghai:${formatIcsDateTime(event.date, event.end)}`);
    lines.push(`SUMMARY:${escapeIcs(`${t.breakTitle} (${event.durationMinutes} min)`)}`);
    lines.push(`DESCRIPTION:${escapeIcs(`${event.leftCode} -> ${event.rightCode}`)}`);
    lines.push("END:VEVENT");
  }

  lines.push("END:VCALENDAR");
  return foldIcsLines(lines).join("\r\n") + "\r\n";
}

function foldIcsLines(lines) {
  const output = [];
  for (const rawLine of lines) {
    if (rawLine.length <= 74) {
      output.push(rawLine);
      continue;
    }
    let line = rawLine;
    output.push(line.slice(0, 74));
    line = line.slice(74);
    while (line.length > 0) {
      output.push(` ${line.slice(0, 73)}`);
      line = line.slice(73);
    }
  }
  return output;
}

function escapeIcs(text) {
  return String(text)
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/,/g, "\\,")
    .replace(/;/g, "\\;");
}

function formatIcsDateTime(date, time) {
  return `${date.replace(/-/g, "")}T${time.replace(":", "")}00`;
}

function formatUtcStamp(date) {
  return date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
}

function minutesToHHMM(totalMinutes) {
  const safe = Math.max(0, totalMinutes);
  const hours = Math.floor(safe / 60);
  const minutes = safe % 60;
  return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}`;
}

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.append(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function getSessionRank(session) {
  const match = session.match(/(\d+)/);
  return match ? Number(match[1]) : 1;
}

function getBoardShort(board) {
  return getText().boardShort[board] || board;
}

function formatImageVenueNote(note) {
  const matches = String(note || "").match(/\bG\d{1,2}\s*(?:\([^)]*\))?\s*:\s*[^;]+/gi) || [];
  return matches
    .map((item) =>
      item
        .replace(/\s*\([^)]*\)\s*(?=:)/g, "")
        .replace(/\s*:\s*/g, ": ")
        .replace(/\s+/g, " ")
        .trim()
    )
    .join("; ");
}

function buildIcsSubjectShort(event) {
  const code = String(event.code || "").toUpperCase();
  const paperName = String(event.paper || "");

  const cieMatch = code.match(/\/(\d+[A-Z]?)$/);
  if (cieMatch) {
    return cieMatch[1];
  }

  const paperPatterns = [
    { regex: /further pure mathematics\s*(\d+)/i, format: "FP" },
    { regex: /pure mathematics\s*(\d+)/i, format: "P" },
    { regex: /statistics?\s*(\d+)/i, format: "S" },
    { regex: /mechanics?\s*(\d+)/i, format: "M" },
    { regex: /decision mathematics?\s*(\d+)/i, format: "D" },
    { regex: /\bcomponent\s*(\d+)/i, format: "C" },
    { regex: /\bunit\s*(\d+)/i, format: "U" },
    { regex: /\bpaper\s*(\d+)/i, format: "P" },
  ];
  for (const item of paperPatterns) {
    const match = paperName.match(item.regex);
    if (match) {
      return `${item.format}${match[1]}`;
    }
  }

  const lastDigit = code.match(/(\d)$/)?.[1];
  if (!lastDigit) {
    return "";
  }
  if (code.startsWith("WFM")) {
    return `FP${lastDigit}`;
  }
  if (code.startsWith("WMA")) {
    return `P${lastDigit}`;
  }
  if (code.startsWith("WST")) {
    return `S${lastDigit}`;
  }
  if (code.startsWith("WME")) {
    return `M${lastDigit}`;
  }
  if (code.startsWith("WDM")) {
    return `D${lastDigit}`;
  }
  if (/^W[A-Z]{2}\d{2}$/.test(code)) {
    return `U${lastDigit}`;
  }
  return "";
}

function formatDateLabel(dateText) {
  const t = getText();
  const [year, month, day] = dateText.split("-").map((item) => Number(item));
  const date = new Date(year, month - 1, day);
  return `${dateText} ${t.weekdays[date.getDay()]}`;
}

function setStatus(text) {
  dom.statusMessage.textContent = text;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
